name: nanodbc

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{matrix.buildname}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            buildname: 'ubuntu'
          - os: windows-latest
            buildname: 'windows'
          - os: macos-latest
            buildname: 'macos'
    env:
      BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
